name: Deploy to Server

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ vars.SSH_PORT }} ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to server
      run: |
        ssh -p ${{ vars.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ vars.SSH_HOST }} << 'EOF'
          # Create project directory if it doesn't exist
          mkdir -p ${{ vars.SSH_DIR }}
          
          # Navigate to project directory
          cd ${{ vars.SSH_DIR }}
          
          # Initialize git repository if it doesn't exist
          if [ ! -d .git ]; then
            git init
            git remote add origin ${{ github.server_url }}/${{ github.repository }}.git
          fi
          
          # Pull latest changes
          git fetch origin main
          git reset --hard origin/main
          
          # Stop existing containers
          docker compose down || true
          
          # Build and start containers
          docker compose up -d --build
          
          # Clean up unused Docker images
          docker image prune -f
        EOF
        
    - name: Verify deployment
      run: |
        # Wait a moment for containers to start
        sleep 10
        
        # Check if the service is responding
        ssh -p ${{ vars.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ vars.SSH_HOST }} << 'EOF'
          cd ${{ vars.SSH_DIR }}
          
          # Check container status
          if docker compose ps --format table | grep -q "Up\|running"; then
            echo "✅ Deployment successful - containers are running"
            docker compose ps
          else
            echo "❌ Deployment failed - containers not running"
            docker compose ps
            echo "--- Container logs ---"
            docker compose logs
            exit 1
          fi
        EOF